#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function main {
    local N=0
    local PID
    local WINDOWID

    parse "$@"

    PID=$( pidof firefox )
    WID=$( wmctrl -lp | grep $PID | awk '{print $1}' )

    while read URL; do
        firefox $URL
        sleep 10
        import -window $WID $N.jpg
        xdotool key --window $WID Ctrl+w
        N=$(( $N + 1 ))
    done
}

main "$@"

#vncserver :11 -geometry 1024x768
#vncserver -clean -kill :11
#$BROWSER --display :11 $URL &
#xdotool key F11
#import -display :11 -window $WINDOWID $N.jpg
